### ISSUE TITLE
Error with adding dual wielder feat

### ISSUE THREAD

**Issue by Demiurgous** [morepurplemorebetter/MPMBs-Character-Record-Sheet#115] opened 2021-06-22 02:49 UTC
I added the dual wielder feat (technically while level 2, as we're starting there) and received this message:
>The custom ApplyWeapon/atkAdd script 'Blood Hunter: Crimson Rite' produced an error! It will be removed from the sheet for now, but please contact the author of the feature to have this issue corrected:
> ReferenceError: BHhemocraftDie is not defined
> fileName: Document-Level:Functions2;
> lineNumber: 3600;
> columnNumber: 7;

**Comment by morepurplemorebetter** [comment] 2021-06-22 11:30
Unfortunately, I'm unable to reproduce this error. The error message you provide is for a Blood Hunter import script. It is thus very unlikely that the error has anything to do with the Dual Wielder feat.

Please make sure you use the latest version of the Blood Hunter script ([found here](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/blob/master/additional%20content/v13/Classes/Blood%20Hunter%202020%20%5BMatthew%20Mercer's%20work%2C%20transcribed%20by%20Smashman%20%26%20MPMB%5D.js)) with the latest version of the sheet (v13.0.4 or v13.0.6-beta2).

Using those latest version, can you walk me through how to reproduce this error, starting with a fresh SRD-only sheet?

**Comment by morepurplemorebetter** [comment] 2021-07-13 09:00
Closing because of lack of information and unable to reproduce.

**Closed by morepurplemorebetter** 2021-07-13 09:00 UTC
Labels: import script
