### ISSUE TITLE
Character limit in dropdown fields?

### ISSUE THREAD

**Issue by Sarkoptesmilbe** [morepurplemorebetter/MPMBs-Character-Record-Sheet#42] opened 2018-01-14 18:49 UTC
One thing I noticed in 12.999 is that you can't freely enter text in dropdown fields anymore - at the very least, it was possible to do that in the armor field. This becomes an issue when, for example, you want to enter a specific magic armor name such as "Black Dragon Scale Mail", which was possible in 12.998
It's also not possible to manually enter resistance types with longer names (although that's less of a problem because you can already select all of them from the list, except details such as "nonmagical") and backgrounds/background features, which are often custom-made.

Would it be possible to remove or extend the limit in all fields?

**Comment by morepurplemorebetter** [comment] 2018-01-14 19:08
None of the fields you mention have a character limit or anything to limit you to what's in the drop-down box. The text in those fields automatically resizes to fit the box. However, once the font size becomes 6, the text won't shrink and the field might overflow. Only on the Colourful sheets does the background feature selection box not auto-resize the text in it, but it still doesn't have a character limit.

Because of your comment, I was afraid I might have accidentally changed one of the fields you are talking about, so I just tested this with all the four different sheets (because you didn't mention with which you had this issue), but I can't reproduce it. Might it be that you are not using the latest Adobe Acrobat version to use the sheet. I have tested this with Adobe Acrobat DC Pro v18.0092005 and Adobe Acrobat DC Reader v18.0092005

Do note that sometimes you will have to first exit a field and then come back to it to be able to edit it. This is a feature of Adobe Acrobat that I have no control over.

Because all the drop-down boxes already have no character limit and you can freely enter text into them, I'm closing this issue.

**Closed by morepurplemorebetter** 2018-01-14 19:08 UTC

**Comment by Sarkoptesmilbe** [comment] 2018-01-14 19:27
I'm using the same DC Reader version (18.009.20050), and encountered the issue on the "Printer Friendly Redesign" sheet. The text resized fine in all other fields, just not in dropdown fields - after fiddling with a few settings, it now resizes as well. Good to know that the problem was on my side, and sorry for troubling you.

**Comment by morepurplemorebetter** [comment] 2018-01-15 10:27
Great that you found out that it is some setting on your side. Would you mind sharing which setting this is, so I can help other people who have this same issue?

**Comment by Sarkoptesmilbe** [comment] 2018-01-26 20:29
Unfortunately, I can't. The problem has since reappeared, and nothing I do seems to fix it. I also can't point to a specific setting that helped that time - for what it's worth, I think it briefly went away after disabling the accessibility support, protected mode and disabling/reenabling JavaScript security settings. I wasn't methodical about it. Then reinstalling Adobe Reader DC fixed it - exactly once. But upon reopening the sheet, the problem reappeared, and further reinstalls also stopped helping.

While the sheet was working as intended and resized text, I also noticed a visual difference to the current faulty state. The dropdown boxes now change appearance when selected, and (on the Printer Friendly sheet) clicking outside a selectable field in the center on the first page prevents any further selections or data entry until clicking somewhere outside the form, as if an "invisible layer" had been selected.

![dropdown](https://user-images.githubusercontent.com/27067598/35459263-a87c6cb6-02df-11e8-9581-16c2c66e9fa8.PNG)

I don't have any knowledge about possible causes or solutions, so it's quite frustrating.

**Comment by morepurplemorebetter** [comment] 2018-02-08 17:51
Sorry for the absence of any response. As this issue is closed I didn't see you added another comment. Truly frustrating how this seems to be appearing and disappearing randomly. Might it have something to do with working on a laptop that is working on battery or not? Or maybe using another screen or not? Or maybe using integrated graphics card or not?

The issue with the invisible layer is just you having selected a field on the sheet which is read-only. The one in the screenshot you send is the field that displays the grey text-boxes which can be switched for the grey lines using the "Text Options" bookmark. This is expected behaviour as you can tab through fields, even those that are read-only in certain circumstances.

**Comment by morepurplemorebetter** [comment] 2018-02-08 17:55
And as you mention accessibility support, that is often a cause of issues like this. If you don't need accessibility support such as having the text on screen read out loud or displayed with bigger, you can just leave it disabled (I do as well). Hopefully it will help in some way...

**Comment by Sarkoptesmilbe** [comment] 2018-02-08 18:18
Sadly, I still have absolutely no idea why this happens or how to fix it. Sometimes there's the issue, and sometimes the sheet works as intended. When it does (such as right this moment), I can't select the "invisible layer" however, be it by clicking or tabbing through, and it doesn't block access to other selectable fields. For the record, I am indeed using a laptop with a graphics card (nVidia GTX 950M) in addition to the integrated processor (Intel HD 520), but so far never on battery, and without issues anywhere else. It truly does look like some hardware quirk on my side, so there's little I can see you doing to help (and no need to reopen the issue)- but thank you anyway. I guess I'll just have to live with it.

Just to contrast it with the earlier screenshot, this is how it looks when resizing etc. work fine, which I think is what it's supposed to look like:
![dropdown](https://user-images.githubusercontent.com/27067598/35990574-bb5a563e-0d04-11e8-8f33-9fe8ebd4477c.PNG)

**Comment by morepurplemorebetter** [comment] 2018-02-08 18:48
This latest screenshot looks the same as it does on my machine, so it is indeed how it is supposed to look like.

My best guess would be that the issue comes from your machine switching from using built-in graphics to the graphics card or visa versa. But I'm no expert, so don't take my word for it ;)
