### ISSUE TITLE
Blood Hunter Crimson Rite not working on Ranged Weapons

### ISSUE THREAD

**Issue by DivertedCircle** [morepurplemorebetter/MPMBs-Character-Record-Sheet#75] opened 2018-11-19 05:16 UTC
Adding the 'Rite' tag to a weapon in the attacks section of a Blood Hunter character isn't adding the rite damage to the weapon properly. In the 'Things Affecting the Attack Calculations' window it states that adding rite to a melee weapons name will add the damage, which it does correctly. The class was update awhile ago to allow rite's to be applied to ranged weapons as well though.

**Comment by morepurplemorebetter** [comment] 2018-11-19 08:59
Thank you for reporting this issue. I was unaware the the Crimson Rite also applied to ranged weapons because it is not mentioned in the feature description. It seems that it has always applied to ranged weapons and that Matt Mercer confirmed so on Twitter, I had just totally missed that.

It is now fixed in the [latest commit](https://github.com/morepurplemorebetter/MPMBs-Character-Record-Sheet/commit/e0219cb1c1b9be96d808256c37858536db621d45).

**Closed by morepurplemorebetter** 2018-11-19 08:59 UTC
